version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    # Alfred for allowing more workers
    command: postgres -c 'max_connections=400'
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - lto-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-need to set the password}
      - POSTGRES_USER=${POSTGRES_USER:-need to set the user}
      - POSTGRES_DB=${POSTGRES_DB:-optuna_db}
    networks:
      - isolated_network

volumes:
    lto-postgres:
      driver: anybox/buttervolume:HEAD
#     Provide path to repository so lookup can provide the correct version of the volume according to committed hash
#      driver_opts:
#        o: "/mnt/flock/flock_finrl"
      #external: true

networks:
  isolated_network:
    #external: true
    name: ${COMPOSE_PROJECT_NAME}

#secrets:
#  gcloud.json:
#    file: ${HOME}/.keys/gcloud-cs221.json
#  alpaca.json:
#    file: ${HOME}/.keys/alpaca-paper.json